export const metadata = {
  title: 'BMS - By GVVL',
  description: 'Generated by Gerard, Víctor, Victoria and Lucía',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
